export const textoTrabalhos: string[] = [
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
  '● Design Social Media',
  '● Estampa De Camisa',
  '● Captação Em Vídeo',
]