export const textoTrabalhos: string[] = [
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
  '● Design para redes sociais',
  '● Estampas camisas',
  '● Produção e edição de videos',
]
